#
# Jekyll config
# ==============================================================================



# Site
# ------------------------------------------------------------------------------

name: Help documentation for the DIVA Media System
description: Help documentation and guides for DIVA Fusion, DIVA Server, DIVA Node, and DIVA Client on Mac and Windows



# Page Defaults
# ------------------------------------------------------------------------------

defaults:
  - # All pages
    scope:
      path: ""
    values:
      layout: "default"
      sortOrder: 1000
  - # v2
    scope:
      path: "v2"
    values:
      version: "v2"
  - # v2 - Admin
    scope:
      path: "v2/admin"
    values:
      category: "admin"
      hide: true
  - # v2 - Users
    scope:
      path: "v2/user"
    values:
      category: "user"
      hide: true
