#
# Jekyll config
# ==============================================================================



# Globals
# ------------------------------------------------------------------------------

exclude: ['images', 'scripts']



# Site
# ------------------------------------------------------------------------------

name: DIVA Help Center
description: Help documentation and guides for DIVA Fusion, DIVA Server, DIVA Node, and DIVA Client on Mac and Windows



# Page Defaults
# ------------------------------------------------------------------------------

defaults:
  - # All pages
    scope:
      path: ""
    values:
      layout: "default"
      sortOrder: 1000
  - # v2
    scope:
      path: "v2"
    values:
      version: "v2"
  - # v2 - Articles
    scope:
      path: "v2/articles"
    values:
      layout: "article-default"
  - # v2 - Admin
    scope:
      path: "v2/admin"
    values:
      category: "admin"
      hide: true
  - # v2 - Editors
    scope:
      path: "v2/editor"
    values:
      category: "editor"
      hide: true
