#
# Jekyll config
# ==============================================================================



# Site
# ------------------------------------------------------------------------------

name: Help documentation for the DIVA Media System
description: Help documentation and guides for DIVA Fusion, DIVA Server, DIVA Node, and DIVA Client on Mac and Windows



# Page Defaults
# ------------------------------------------------------------------------------

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
      sortOrder: 0
  - # v2
    scope:
      path: "v2"
    values:
      version: "v2"
  - # v2 Admin
    scope:
      path: "v2/admin"
    values:
      category: "admin"
      categoryTitle: "Admin Guide"
  - # v2 - Admin - Drives
    scope:
      path: "v2/admin/drives"
    values:
      topic: "drives"
      topicTitle: "Drives"
  - # v2 - Admin - Nodes
    scope:
      path: "v2/admin/nodes"
    values:
      topic: "nodes"
      topicTitle: "Nodes"
