#
# Jekyll config
# ==============================================================================



# Globals
# ------------------------------------------------------------------------------

exclude: ['images', 'scripts']
plugins:
  - jekyll-sitemap



# Site
# ------------------------------------------------------------------------------

name: DIVA Help Center
description: Help documentation and guides for DIVA Fusion, DIVA Server, DIVA Node, and DIVA Client on Mac and Windows
url: "https://help.group6.co.nz"



# Page Defaults
# ------------------------------------------------------------------------------

defaults:
  - # All pages
    scope:
      path: ""
    values:
      layout: "default"
      sortOrder: 1000
  - # v2 - Articles
    scope:
      path: "v2/articles"
    values:
      layout: "article-default"
      tags: v2
  - # v3 - Articles
    scope:
      path: "v3/articles"
    values:
      layout: "article-default"
      tags: v3
