#
# Jekyll config
# ==============================================================================



# Site
# ------------------------------------------------------------------------------

name: Help documentation for the DIVA Media System
description: Help documentation and guides for DIVA Fusion, DIVA Server, DIVA Node, and DIVA Client on Mac and Windows
